<?php

namespace App\Service;

use App\Models\Role;

class Permissions
{
    const EMPLOYEE_SUPER_ADMIN_VIEW = [Role::SUPER_ADMIN];
    const EMPLOYEE_SUPER_ADMIN_CREATE = [];
    const EMPLOYEE_SUPER_ADMIN_UPDATE = [Role::SUPER_ADMIN];
    const EMPLOYEE_SUPER_ADMIN_DELETE = [];

    const EMPLOYEE_DIRECTOR_VIEW = [Role::SUPER_ADMIN, Role::DIRECTOR];
    const EMPLOYEE_DIRECTOR_CREATE = [Role::SUPER_ADMIN];
    const EMPLOYEE_DIRECTOR_UPDATE = [Role::SUPER_ADMIN, Role::DIRECTOR];
    const EMPLOYEE_DIRECTOR_DELETE = [Role::SUPER_ADMIN];

    const EMPLOYEE_ADMINISTRATOR_VIEW = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR];
    const EMPLOYEE_ADMINISTRATOR_CREATE = [Role::SUPER_ADMIN, Role::DIRECTOR];
    const EMPLOYEE_ADMINISTRATOR_UPDATE = [Role::SUPER_ADMIN, Role::DIRECTOR];
    const EMPLOYEE_ADMINISTRATOR_DELETE = [Role::SUPER_ADMIN, Role::DIRECTOR];

    const EMPLOYEE_SIMPLE_USER_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR];


    const COMPANY_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR];

    const COUNTRY_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR];

    const CITY_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR];

    const RESTAURANT_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR];

    const CATEGORY_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR, Role::MENU_MANAGER];

    const INGREDIENT_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR, Role::MENU_MANAGER];

    const PRODUCT_ALL_ACTIONS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR, Role::MENU_MANAGER];


    const ADMIN_PANEL_ACCESS = [Role::SUPER_ADMIN, Role::DIRECTOR, Role::ADMINISTRATOR, Role::MENU_MANAGER];
}
